#!/usr/bin/env python3
"""Emit esp32-s3/src/canopen_objects.h from canopen.txt (sub0 objects only).

    python3 canopen/gen_canopen_table.py            # rewrites the header
    python3 canopen/gen_canopen_table.py --check    # self-check only

The firmware's CANopen poller (-DCANOPEN_POLL) sweeps this table in a loop.
Re-run after re-dumping the dictionary so the firmware tracks canopen.txt.
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "canopen.txt")
DST = os.path.join(HERE, "..", "esp32-s3", "src", "canopen_objects.h")
LINE_RE = re.compile(r"^0x([0-9A-Fa-f]{4}):0x00\s+value=")

def load(path=SRC):
    with open(path) as f:
        idx = sorted({int(m.group(1), 16) for m in map(LINE_RE.match, f) if m})
    assert idx and idx[0] >= 0x1000 and idx[-1] <= 0xFFFF, "bad index range"
    return idx

def render(idx):
    out = ["// GENERATED by canopen/gen_canopen_table.py from canopen/canopen.txt — do not edit.",
           "// Sub-index 0 objects the Curtis 1238E (CANopen node 0x28) answers SDO upload for.",
           "#pragma once", "#include <stdint.h>",
           f"static const uint16_t kCanopenObjects[{len(idx)}] = {{"]
    for i in range(0, len(idx), 8):
        out.append("    " + ", ".join(f"0x{v:04X}" for v in idx[i:i+8]) + ",")
    out.append("};")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    idx = load()
    text = render(idx)
    assert text.count("0x") == len(idx) + 1, "render dropped entries"   # +1 for node 0x28 in comment
    if "--check" in sys.argv:
        print(f"ok: {len(idx)} objects"); sys.exit(0)
    with open(DST, "w") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(DST)}: {len(idx)} objects")
