"""Bake WiFi identity strings into the firmware from env vars.

WIFI_SSID / WIFI_PASS (the station join) and AP_SSID / AP_PASS / MDNS_NAME
(the board's own hotspot) are read from the environment (e.g. by sourcing
.env) and written as #defines into a generated header, wifi_overrides.h, in
the build dir; main.cpp includes it via __has_include. A header rather than
-D flags because a command-line value is expanded by SCons and again by the
shell, which silently mangles $ and backslashes — and a header keeps the
password out of the compiler command line and compile_commands.json. Unset
variables are omitted, so the firmware falls back to the defaults compiled
into src/main.cpp and the default build is unchanged.

Also prints a build-log summary of the station credentials, because an
unset or typo'd env var otherwise compiles silently into an AP-only image.
"""
import os

Import("env")  # noqa: F821 — provided by PlatformIO


def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = ["// Generated by inject_build_overrides.py — do not edit.\n"]
for name in ("WIFI_SSID", "WIFI_PASS", "AP_SSID", "AP_PASS", "MDNS_NAME"):
    value = os.environ.get(name)
    if value:
        lines.append(f"#define {name} {c_string(value)}\n")
content = "".join(lines)

gen_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
os.makedirs(gen_dir, exist_ok=True)
header = os.path.join(gen_dir, "wifi_overrides.h")
# Rewrite only on change so credential-identical rebuilds stay no-ops.
try:
    with open(header) as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False
if not unchanged:
    with open(header, "w") as f:
        f.write(content)
env.Append(CPPPATH=[gen_dir])  # noqa: F821

ssid = os.environ.get("WIFI_SSID") or ""
password = os.environ.get("WIFI_PASS") or ""
if ssid and password:
    print(f'WiFi STA credentials: SSID "{ssid}", password set ({len(password)} chars)')
elif ssid:
    print("!" * 72)
    print(f'WARNING: WIFI_SSID "{ssid}" is set but WIFI_PASS is empty/unset —')
    print("         the firmware will try to join with no password.")
    print("!" * 72)
elif password:
    print("!" * 72)
    print("WARNING: WIFI_PASS is set but WIFI_SSID is empty/unset —")
    print("         building AP-only firmware; the station will be disabled.")
    print("!" * 72)
else:
    print("WiFi STA credentials: none set — AP-only build (station disabled).")
