"""Bake the board's own hotspot identity into the firmware from env vars.

AP_SSID / AP_PASS / MDNS_NAME are read from the environment (e.g. by sourcing
.env) and written as #defines into a generated header, wifi_overrides.h, in
the build dir; main.cpp includes it via __has_include. A header rather than
-D flags because a command-line value is expanded by SCons and again by the
shell, which silently mangles $ and backslashes — and a header keeps the
password out of the compiler command line and compile_commands.json. Unset
variables are omitted, so the firmware falls back to the defaults compiled
into src/main.cpp and the default build is unchanged.

Station (home/bench network) credentials are deliberately NOT compiled in —
they live only in NVS, set at runtime via /wifi — so a release image can't
ship with the builder's network baked in. WIFI_SSID / WIFI_PASS in the
environment are ignored, with a warning.
"""
import os

Import("env")  # noqa: F821 — provided by PlatformIO


def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = ["// Generated by inject_build_overrides.py — do not edit.\n"]
for name in ("AP_SSID", "AP_PASS", "MDNS_NAME"):
    value = os.environ.get(name)
    if value:
        lines.append(f"#define {name} {c_string(value)}\n")
content = "".join(lines)

gen_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
os.makedirs(gen_dir, exist_ok=True)
header = os.path.join(gen_dir, "wifi_overrides.h")
# Rewrite only on change so credential-identical rebuilds stay no-ops.
try:
    with open(header) as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False
if not unchanged:
    with open(header, "w") as f:
        f.write(content)
env.Append(CPPPATH=[gen_dir])  # noqa: F821

if os.environ.get("WIFI_SSID") or os.environ.get("WIFI_PASS"):
    print("!" * 72)
    print("WARNING: WIFI_SSID/WIFI_PASS are ignored — station credentials are")
    print("         no longer compiled in. Set them at runtime via /wifi.")
    print("!" * 72)
